# -*- coding: utf-8 -*-
"""Exemplos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OdUEWLRjLOFPnwy_x6LJxAtwpHCjI5y4

**Bibliotecas**
"""

import numpy as np

"""Entradas e Pesos

"""

entradas =[1, 7, 5]
pesos = [0.8, 0.1, 0]

"""Soma e multiplica"""

#Forma 1 - sem a utilização da biblioteca numpy
def soma1(e, p):
  s = 0
  for i in range(3):
    s=s+e[i]*p[i]
  return s

#Forma 2 - com a utilização da biblioteca numpy
def soma(e, p):
  e=np.array(e)
  p=np.array(p)
  return e.dot(p)

"""Step Function"""

def stepFunction(soma):
    if (soma > 0):
        return 1
    return 0

"""Chamada da execução do código"""

s = soma1(entradas, pesos)
print(s)
s = soma(entradas, pesos)
print(s)
r=stepFunction(s)
print(r)